### ISSUE TITLE
Spamming minifier makes player gigantic

### ISSUE THREAD

**Issue by TheMarrix** [TTT-2/ttt2-item_minifier#1]
Left-clicking while shrinking makes the player gigantic. Players will get bigger with each time they do this. This stays until mapchange.

**Comment by TimGoll** [comment]
Wow, thank you! I've seen gigantic players in a few videos but was unable to reproduce this!

So if you doubleclick it makes you gigantic? Or how do I reproduce this?

**Comment by TheMarrix** [comment]
You get the bug when you leftclick while in the process of shrinking.
If you just spam leftclick you will get it pretty much always.

**Comment by TheMarrix** [comment]
Your firstperson view will stay normal during the bug. I only see it in thirdperson or when another player has it.

**Comment by TimGoll** [comment]
Thanks. I have some time next week and I'll try to fix it! :)

**Comment by TimGoll** [comment]
Updated in the workshop. Please report back if the problem persists
